package com.view;

import com.Kiosk;
import com.controller.CheckoutController;
import com.controller.Controller;
import com.controller.InventoryController;
import com.model.JsonObject;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.Date;

public class StockView extends DataView {
    private JScrollPane scrollPane;
    private JTable table;
    private JButton reorderButton;
    public StockView(Kiosk window){
        setWindow(window);
        initialise();
    }

    public void reorder(){
        // Ask controller to reorder an item
        int rowIndex = table.getSelectedRow();
        if (rowIndex != -1){
            // Create dialog form asking user to specify quantity
            String barcode = table.getValueAt(rowIndex, 0).toString();
            float supplierPrice = Float.parseFloat(table.getValueAt(rowIndex, 5).toString());
            JLabel barcodeField = new JLabel(barcode);
            SpinnerNumberModel model = new SpinnerNumberModel();
            model.setMinimum(0);
            model.setValue(0);
            JSpinner quantityField = new JSpinner(model);
            JLabel costField = new JLabel("£0.00");
            quantityField.addChangeListener(e ->
            {
                // Recalculate cost whenever quantity changes
                int quantity = (int) quantityField.getValue();
                float cost = quantity * supplierPrice;
                costField.setText(String.format("£%.2f", cost));
            });
            Object[] fields = {
                    "Barcode:", barcodeField,
                    "Order quantity:", quantityField,
                    "Cost:", costField
            };
            int chosenOption = JOptionPane.showConfirmDialog(this, fields, "Order Item", JOptionPane.OK_CANCEL_OPTION);
            if (chosenOption == JOptionPane.OK_OPTION){
                // Ask controller to create the order
                int quantity = (int) quantityField.getValue();
                float cost = Float.parseFloat(costField.getText().replaceAll("[^0-9.]", ""));
                // The key (OrderID) is generated by the controller, not the view
                controller.updateModel(Controller.CREATE_ORDER, new JsonObject(new JsonObject.JsonBuilder("")
                .setItemBarcode(barcode)
                .setQuantityPurchased(quantity)
                .setCost(cost)));
            }
        }
    }

    @Override
    public void create() {
        // Ask controller to create a new stock item

        // Display dialog to get item info
        JTextField barcodeField = new JTextField();
        JTextField nameField = new JTextField();
        JTextField quantityField = new JTextField();
        JTextField reorderLvlField = new JTextField();
        JTextField salePriceField = new JTextField();
        JTextField supplierPriceField = new JTextField();
        Object[] fields = {
                "Barcode:", barcodeField,
                "Name:", nameField,
                "Quantity:", quantityField,
                "Reorder level:", reorderLvlField,
                "Sale price:", salePriceField,
                "Supplier price:", supplierPriceField
        };

        int chosenOption = JOptionPane.showConfirmDialog(this, fields , "New Item", JOptionPane.OK_CANCEL_OPTION);
        if (chosenOption == JOptionPane.OK_OPTION){
            // Ask controller to create item
            try {
                String barcode = barcodeField.getText();
                String name = nameField.getText();
                int quantity = Integer.parseInt(quantityField.getText());
                int reorderLvl = Integer.parseInt(reorderLvlField.getText());
                // First remove any characters that are not either . or digits (to remove any currency symbols)
                float salePrice = Float.parseFloat(salePriceField.getText().replaceAll("[^0-9.]", ""));
                float supplierPrice = Float.parseFloat(supplierPriceField.getText().replaceAll("[^0-9.]", ""));
                // Create JsonObject for new item
                JsonObject newItem = new JsonObject(new JsonObject.JsonBuilder(barcode)
                        .setName(name)
                        .setQuantityInStock(quantity)
                        .setReorderLevel(reorderLvl)
                        .setSalePrice(salePrice)
                        .setSupplierPrice(supplierPrice));
                // Ask controller to create new item
                controller.updateModel(Controller.CREATE_STOCKITEM, newItem);
            }
            catch (NumberFormatException err){
                JOptionPane.showMessageDialog(this, "Unable to add new item as one the fields was invalid");
            }
        }
    }

    @Override
    public void delete() {
        // Ask controller to delete the selected stock item
        int selectedIndex = table.getSelectedRow();
        if (selectedIndex != -1){
            String barcode = table.getValueAt(selectedIndex, 0).toString();
            controller.updateModel(Controller.DELETE_STOCKITEM, new JsonObject(new JsonObject.JsonBuilder(barcode)));
        }
    }

    @Override
    public void update() {
        // Ask controller to modify the selected stock item
        int selectedIndex = table.getSelectedRow();
        if (selectedIndex != -1){
            // Display dialog to get needed info
            String currentBarcode = table.getValueAt(selectedIndex, 0).toString();
            String currentName = table.getValueAt(selectedIndex, 1).toString();
            String currentQuantity = table.getValueAt(selectedIndex, 2).toString();
            String currentReorderLvl = table.getValueAt(selectedIndex, 3).toString();
            String currentSalePrice = table.getValueAt(selectedIndex, 4).toString();
            String currentSupplierPrice = table.getValueAt(selectedIndex, 5).toString();
            JTextField barcodeField = new JTextField();
            barcodeField.setText(currentBarcode);
            barcodeField.setEditable(false);  // Barcode cannot be edited
            JTextField nameField = new JTextField();
            nameField.setText(currentName);
            JTextField quantityField = new JTextField();
            quantityField.setText(currentQuantity);
            JTextField reorderLvlField = new JTextField();
            reorderLvlField.setText(currentReorderLvl);
            JTextField salePriceField = new JTextField();
            salePriceField.setText(currentSalePrice);
            JTextField supplierPriceField = new JTextField();
            supplierPriceField.setText(currentSupplierPrice);
            Object[] fields = {
                    "Barcode:", barcodeField,
                    "Name:", nameField,
                    "Quantity:", quantityField,
                    "Reorder level:", reorderLvlField,
                    "Sale price:", salePriceField,
                    "Supplier price:", supplierPriceField
            };

            int chosenOption = JOptionPane.showConfirmDialog(this, fields , "Edit Item", JOptionPane.OK_CANCEL_OPTION);
            if (chosenOption == JOptionPane.OK_OPTION){
                // Ask controller to modify item
                try {
                    // Ask controller to update any items that have been changed
                    if (!nameField.getText().equals(currentName)){
                        controller.updateModel(Controller.UPDATE_ITEM_NAME, new JsonObject(new JsonObject.JsonBuilder(currentBarcode)
                        .setName(nameField.getText())));
                    }
                    if (!quantityField.getText().equals(currentQuantity)){
                        int newQuantity = Integer.parseInt(quantityField.getText());
                        controller.updateModel(Controller.UPDATE_ITEM_QUANTITY, new JsonObject(new JsonObject.JsonBuilder(currentBarcode)
                        .setQuantityInStock(newQuantity)));
                    }
                    if (!reorderLvlField.getText().equals(currentReorderLvl)){
                        int newLevel = Integer.parseInt(reorderLvlField.getText());
                        controller.updateModel(Controller.UPDATE_REORDER_LEVEL, new JsonObject(new JsonObject.JsonBuilder(currentBarcode)
                        .setReorderLevel(newLevel)));
                    }
                    String priceFieldValue = salePriceField.getText().replaceAll("[^0-9.]", "");
                    if (!priceFieldValue.equals(currentSalePrice)){
                        float newPrice = Float.parseFloat(priceFieldValue);
                        controller.updateModel(Controller.UPDATE_SALE_PRICE, new JsonObject(new JsonObject.JsonBuilder(currentBarcode)
                        .setSalePrice(newPrice)));
                    }
                    priceFieldValue = supplierPriceField.getText().replaceAll("[^0-9.]", "");
                    if (!priceFieldValue.equals(currentSupplierPrice)){
                        float newPrice = Float.parseFloat(priceFieldValue);
                        controller.updateModel(Controller.UPDATE_SUPPLIER_PRICE, new JsonObject(new JsonObject.JsonBuilder(currentBarcode)
                                .setSupplierPrice(newPrice)));
                    }
                }
                catch (NumberFormatException err){
                    JOptionPane.showMessageDialog(this, "Unable to modify item as one the fields was invalid");
                }
            }
        }

    }

    @Override
    public void addToDisplay(String key, Object... values) {
        if (values.length == 5){
            Object[] row = new Object[6];
            row[0] = key;  // Barcode
            row[1] = values[0];  // Name
            row[2] = values[1];  // Quantity
            row[3] = values[2];  // Reorder level
            row[4] = String.format("%.2f", (float) values[3]);  // Sale price
            row[5] = String.format("%.2f", (float) values[4]);  // Supplier price
            ((DefaultTableModel) table.getModel()).addRow(row);
            itemsInTable.add(key);
        }
    }

    @Override
    public void editDisplayedItem(String key, String fieldToChange, Object newValue) {
        int rowIndex = getItemIndex(key);
        if (rowIndex != -1){
            switch (fieldToChange){
                case "name":
                    table.setValueAt(newValue, rowIndex, 1);
                    break;
                case "quantityInStock":
                    table.setValueAt(newValue, rowIndex, 2);
                    break;
                case "reorderLevel":
                    table.setValueAt(newValue, rowIndex, 3);
                    break;
                case "salePrice":
                    table.setValueAt(String.format("%.2f", (float) newValue), rowIndex, 4);
                    break;
                case "supplierPrice":
                    table.setValueAt(String.format("%.2f", (float) newValue), rowIndex, 5);
                    break;
            }
        }
    }

    @Override
    public void removeDisplayedItem(String key) {
        int rowIndex = getItemIndex(key);
        if (rowIndex != -1){
            ((DefaultTableModel) table.getModel()).removeRow(rowIndex);
            itemsInTable.remove(rowIndex);
            if (table.getSelectedRow() == -1){
                // No rows are selected anymore, so disable buttons
                deleteItemButton.setEnabled(false);
                editButton.setEnabled(false);
                reorderButton.setEnabled(false);
            }
        }
    }

    @Override
    protected void initialiseTable(){
        gotoStockButton.setEnabled(false);
        table = new JTable(new DefaultTableModel(new String[]{"Barcode", "Name", "Quantity in Stock", "Reorder Level", "Sale Price (£)", "Supplier Price (£)"}, 0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });

        table.setDefaultRenderer(Object.class, new DefaultTableCellRenderer(){
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                // Override the cell renderer's getTableCellRendererComponent method to colour cells in rows where quantity is below reorder level

                // Get component for drawing the cell
                Component renderer = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                int quantityInStock;
                int reorderLevel;
                try{
                    quantityInStock = Integer.parseInt(table.getValueAt(row, 2).toString());
                    reorderLevel = Integer.parseInt(table.getValueAt(row, 3).toString());
                }
                catch (NumberFormatException e){
                    // If the values cannot be parsed, just assume the row does not need highlighting
                    quantityInStock = 0;
                    reorderLevel = 0;
                }
                // Highlight cell if this row's quantityInStock is below reorder level
                if (quantityInStock < reorderLevel){
                    renderer.setBackground(Color.RED);
                }
                else{
                    renderer.setBackground(Color.WHITE);
                }
                return renderer;
            }
        });

        scrollPane = new JScrollPane(table);
        table.getTableHeader().setReorderingAllowed(false);
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.gridx = 0;
        constraints.gridy = 1;
        constraints.gridwidth = 5;
        constraints.weighty = 0.9;
        constraints.weightx = 0.1;
        constraints.fill = GridBagConstraints.BOTH;
        add(scrollPane, constraints);
        // Add reorder button
        reorderButton = new JButton("Reorder");
        constraints.weightx = 0;
        constraints.weighty = 0;
        constraints.fill = GridBagConstraints.NONE;
        constraints.anchor = GridBagConstraints.LAST_LINE_START;
        constraints.gridx = 3;
        constraints.gridy = 2;
        reorderButton.setEnabled(false);
        add(reorderButton, constraints);

        addItemButton.addActionListener(e -> {
            create();
        });

        deleteItemButton.addActionListener(e -> {
            delete();
        });

        editButton.addActionListener(e -> {
            update();
        });

        reorderButton.addActionListener(e -> {
            reorder();
        });

        table.getSelectionModel().addListSelectionListener(e -> {
            // Enable delete, edit, and reorder buttons when row selected
            editButton.setEnabled(true);
            deleteItemButton.setEnabled(true);
            reorderButton.setEnabled(true);
        });
    }
}
